### ISSUE TITLE
Question: Difference to Ideapad mode

### ISSUE THREAD

**Issue by mo8it** [AzzamAlsharafi/ideapad-controls-gnome-extension#1]
What is the difference between this extension and Ideapad mode?
https://extensions.gnome.org//extension/4331/ideapad-mode/

**Comment by AzzamAlsharafi** [comment]
I made this extension mainly because I wanted the ability to hide the options that I don't need. I personally only want Conservation mode and camera control, so for me the other options are just taking space. 

In IdeaPad Control you can choose which options to keep and which options to hide from the settings window.

Also, it was a fun project and a new thing to learn. :)

**Comment by mo8it** [comment]
Thanks for the explanation!
It would be awesome if you could add this information to the README.md for others who also want to know what the difference is ;)
