### ISSUE TITLE
Asks for password to change any option.

### ISSUE THREAD

**Issue by ghost** [AzzamAlsharafi/ideapad-controls-gnome-extension#5]
I have all options enabled except USB charging because it just doesn't show. I have it set to be in the system control center. For some reason when I toggle anything it just asks for a password? Lenovo Ideapad 3 14IML05 (meaning it's a 14"), on Fedora 37 Workstation beta with Gnome 43.0.

**Comment by AzzamAlsharafi** [comment]
The extension only shows available option that are accessible from **/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/**, if an option isn't available it means the extension can't find its respective file, either because the file doesn't exist or it has a different name than the one the extension is looking for. For USB charging the file name is **usb_charging**. So can you send me the output of `ls /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/`?

As for the password problem, unfortunately I don't know of any other way to do it, because the extension needs sudo privilege in order to edit the file inside **/sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/**, so it needs to ask for the password everytime.

**Comment by ghost** [comment]
[nostii@lenowo-ideapad ~]$ sudo ls /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/
[sudo] password for nostii: 
Sorry, try again.
[sudo] password for nostii: 
camera_power	   driver_override  fn_lock   power	 touchpad
conservation_mode  fan_mode	    input     rfkill	 uevent
driver		   firmware_node    modalias  subsystem

**Comment by AzzamAlsharafi** [comment]
As you can see there's no option for USB charging in your laptop, at least not from the ideapad_acpi driver, which is what the extension uses to control the ideapad options.
